T_B_O0:                # B → O at theta = 0  (calibration 전 임시값: identity rotation)
  translation: [0.7557, 0.0069, 0.7]  # [x, y, z] in meters, init_position : [0.2059, 0.0069, 0.120]
  rotation_quat: [0.0, 0.0, 0.0, 1.0]   # [qx, qy, qz, qw] — identity
